[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]] #snippet
repo = 'Shougo/neosnippet'

[[plugins]] #snippet file
repo = 'Shougo/neosnippet-snippets'

[[plugins]] #snippet file
repo =  'honza/vim-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]] #manual閲覧
repo = 'thinca/vim-ref'

[[plugins]] #ctags list
repo = 'vim-scripts/taglist.vim'

[[plugins]] #asynchronous code check
repo = 'w0rp/ale'

[[plugins]] #html5 syntax
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]] #text object extention
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]] #file tree
repo = 'scrooloose/nerdtree'

[[plugins]] #git plugin
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]] #indent visualization
repo = 'Yggdroot/indentLine'

[[plugins]] #clorscheme
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]] #auto insetr close symbols
repo = 'cohama/lexima.vim'

[[plugins]] #use gist on vim
repo = 'lambdalisue/vim-gista'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]] #grep tool
repo = 'fuenor/qfixgrep'

[[plugins]] #markdown
repo = 'gabrielelana/vim-markdown'

[[plugins]] # preview
repo = 'greyblake/vim-preview'

[[plugins]] # indent php and html
repo = 'captbaritone/better-indent-support-for-php-with-html'
