[[plugins]]
repo = 'Shougo/neco-vim'
on_source = ['deoplete.vim']

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = ['deoplete.vim']

[[plugins]]
repo = 'ujihisa/neco-look'
on_source = ['deoplete.vim']

[[plugins]] #snippet
repo = 'Shougo/neosnippet'
on_source = ['neocomplete.vim']
hook_source = 'source ~/dotfiles/nvim/plugin_settings/neosnippet.vim'

[[plugins]] #snippet file
repo = 'Shougo/neosnippet-snippets'
on_source = ['neocomplete.vim']

[[plugins]] #snippet file
repo = 'honza/vim-snippets'
on_source = ['neocomplete.vim']
